### ISSUE TITLE
paper-input breaking vulcanize gulp task.

### ISSUE THREAD

**Issue by runia1** [PolymerElements/paper-input#345]
Using Polymer Starter Kit, when including paper-input in my elements.html file like such:

`<link rel="import" href="../bower_components/paper-input/paper-input.html">`

then running:

`gulp default`

Build goes smoothly until it attempts to vulcanize the elements.html, when I take out the include for paper-input the other includes are able to vulcanize and build finishes.  Any ideas what may be causing this?  I can provide more info if needed.

**Comment by runia1** [comment]
After doing some investigation I found that the problem was actually being caused by <iron-input> that was included by <paper-input>.  I also found a bug in the gulp-vulcanize build tool.  gulp-vulcanize was not reporting the error, I don't know enough about node to fully understand why, but here's what I found:

By adding a console.log() to gulp-vulcanize's index.js I was able to finally see where the problem was occurring:
`(new Vulcanize(opts)).process(file.path, function(err, inlinedHtml) {
      if(err) {
        console.log('error on vulcanize' + err);
        cb(new gutil.PluginError('gulp-vulcanize', err, {fileName: file.path}));
        return;
      }

      file.contents = new Buffer(inlinedHtml);
      cb(null, file);
    }.bind(this));`

Then when I ran:
`$ gulp default`
It finally printed out the following error message:
`[11:25:37] Starting 'vulcanize'...
error on vulcanizeError: Error parsing script in /Users/mar/PhpstormProjects/skedMeWeb2/app/bower_components/iron-input/iron-input.html at 75:13
Error: Line 62: Unexpected token :
    at throwError (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2133:5)
    at consumeSemicolon (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2214:9)
    at parseStatement (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:4361:5)
    at parseStatement (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:4356:23)
    at parseSourceElement (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:5187:16)
    at parseStatementList (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3616:21)
    at parseBlock (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3632:13)
    at parseStatement (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:4289:16)
    at parseStatement (/Users/mar/PhpstormProjects/skedMeWeb2/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:4356:23)
`
From here I was able to see that <iron-input> was causing the problem.  The fact that I had to put a console.log() in there to see the error makes me think that gulp-vulcanize's cb (callback) isn't working the way they intended.

Lastly, in <iron-input> I found the culprit towards the end of the comment block:
` 
  <
  input
  is = "iron-input"
  prevent - invalid - input
  allowed - pattern = "[0-9]" >

  @
  hero
  hero.svg
  @
  demo
  demo / index.html
  * /

  Polymer({`

Why the Comment was all screwed up like that I do not know.  I've checked the current master branch and the comment does not look like that, so possibly it got screwed up by bower or some other reason.
