### ISSUE TITLE
Not working with Polymer Starter Kit

### ISSUE THREAD

**Issue by chwzr** [PolymerElements/paper-input#678]
### Description
I've installed it on a blank polymer 3 starter kit.
got following error:

Is this bc there is a separate @polymer node_module installed in subfolder? 

### Steps to reproduce

 polymer starter kit 3
2. npm install @polymer/paper-input --save
3. import like in the docs..
4. polymer serve

4. see error in console:

```javascript
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at Polymer (http://localhost:8081/node_modules/@polymer/polymer/lib/legacy/polymer-fn.js:43:18)
    at http://localhost:8081/node_modules/@polymer/iron-input/node_modules/@polymer/iron-meta/iron-meta.js:141:1
```
-->

### Browsers Affected

- [x ] Chrome

**Comment by fagnercarvalho** [comment]
To anyone that get here I resolved this issue by running:

`
- rm
 -rf node_modules package-lock.json
npm i
`

**Comment by chwzr** [comment]
exactly this is solving the issue.
